import type { Caption, ModelSettings } from './types';
export const steps = ['Locate connection','Open work area','Fuse and tap','Connect service','Test and restore'];
const tapping: Caption[] = [
 {title:'1. Locate the connection',body:'Verify the live main and retained meter. Agree the shutdown, resident access and fire arrangements before work.'},
 {title:'2. Expose sufficient working length',body:'Buried: excavate and support the trench. Channel: lift enough covers and protect the open walkway. Fittings, scrapers and clamps must fit.'},
 {title:'3. Top-mounted tee, side-facing outlet',body:'The cutter accesses the main from above; the service leaves the side of the tee towards the villa. This is a review preference for access below removable covers, subject to the selected fitting and designer approval. It is not a vent.'},
 {title:'4. Connect to the retained villa meter',body:'OD25 PE100 HDPE runs straight from the tee outlet towards the retained villa meter. For the channel, this revised concept replaces the S-curve. Pipe movement and fitting loads still need to be checked; REQ-002 p. 11 and BOQ B3 still describe the previous loop.'},
 {title:'5. Test before restoration',body:'Complete the approved pressure, hygiene and restoration checks. Reinstate the trench or refit covers. This is a visual sequence, not a work instruction.'},
];
export function caption(s: ModelSettings): Caption {
 if(s.view==='network') return {title:'Full layout, then each distribution area',body:'Start the full flyover for an overview, northern, central and southern distribution areas, then a final plan view. Full layout returns from any close-up. Select a component to inspect it; dragging or a camera action stops the tour. Routes follow the supplied CAD plan. Vertical levels remain illustrative.'};
 if(s.view==='run')return {title:'Along the route: chamber, bend and take-offs',body:'Two legs of OD110 main joined by a long-radius bend, one isolation valve in a chamber, and two villa take-offs — switch on water flow to follow tracers through all of it. The asset schedule lists 13 valves and 3 air valves; their chambers, the bend radii and the cover details are not yet designed, so everything here is indicative and the lengths are illustrative rather than taken from the CAD plan.'};
 if(s.view==='tapping')return tapping[s.step];
 if(s.view==='weather')return s.option==='channel'?{title:'Collection still needs a discharge route',body:'Your intent is a sloping floor to simple low-point or corner collection. Actual levels, falls and an outlet are unresolved. Rain and sand shown here are qualitative illustrations; no quantity or drainage capacity is predicted.'}:{title:'Fewer exposed components to maintain',body:'Conventional burial avoids a continuous channel, its covers and its drainage points. It still needs correct bedding, utility clearances and repair excavation. Rain and sand symbols do not represent measured conditions.'};
 return s.option==='buried'?{title:'Option One: simpler routine operation',body:'The cut-away exposes sand or fine granular bedding and surround, compacted backfill, pavement sub-base and paving. Material grading and layer thicknesses remain subject to approval. Future repairs require excavation and reinstatement. The 1,000 mm walkway cover and 600 mm trench width are project pricing assumptions.'}:{title:'Option Two: access has conditions',body:'The 600 × 450 mm clear channel provides access when covers are lifted. It also adds covers, frames, supports and drainage to maintain. Working space must be demonstrated with actual fittings and tools.'};
}
