import type { Caption, ModelSettings } from './types';
export const steps = ['Locate connection','Open work area','Fuse and tap','Connect service','Test and restore'];
const tapping: Caption[] = [
 {title:'1. Locate the connection',body:'Verify the live main and retained meter. Agree the shutdown, resident access and fire arrangements before work.'},
 {title:'2. Expose sufficient working length',body:'Buried: excavate and support the trench. Channel: lift enough covers and protect the open walkway. Fittings, scrapers and clamps must fit.'},
 {title:'3. Upper-quadrant electrofusion saddle',body:'The saddle is positioned 45° from the crown towards the villa, approximately 10:30 when viewed along the main with the villa on the left. The branch uses an electrofusion saddle and a factory-formed swept outlet. Exact fitting dimensions and approval remain outstanding.'},
 {title:'4. Sweep gently towards the retained meter',body:'The OD25 service follows a tangent-continuous formed sweep into the existing wall seal and retained meter alignment. No sharp 90° elbow or forced cold bend is shown at the saddle. The displayed sweep is illustrative, not a permitted pipe bending radius. Fitting selection, support and thermal movement checks are required to establish saddle loads.'},
 {title:'5. Test before restoration',body:'Complete the approved pressure, hygiene and restoration checks. Reinstate the trench or refit covers. This is a visual sequence, not a work instruction.'},
];
export function caption(s: ModelSettings): Caption {
 if(s.view==='network') return {title:'Full layout, then each distribution area',body:'Start the full flyover for an overview, northern, central and southern distribution areas, then a final plan view. Full layout returns from any close-up. Select a component to inspect it; dragging or a camera action stops the tour. Routes follow the supplied CAD plan. Vertical levels remain illustrative.'};
 if(s.view==='run')return {title:'Main C supplies both villa-side pipelines',body:'Follow blue flow along the single Main C into Main A at Tee A and Main B at Tee B. Main B uses a buried sleeved stub, as shown on MB-PW-Z5-005, page 1 of the supplied design drawings. Each side then supplies its own villas through OD25 services and retained meters. No villa service crosses the asphalt road. This shortened presentation model preserves that connection arrangement; road width, row offsets and levels are illustrative.'};
 if(s.view==='tapping')return tapping[s.step];
 if(s.view==='weather')return s.option==='channel'?{title:'Collection still needs a discharge route',body:'Your intent is a sloping floor to simple low-point or corner collection. Actual levels, falls and an outlet are unresolved. Rain and sand shown here are qualitative illustrations; no quantity or drainage capacity is predicted.'}:{title:'Fewer exposed components to maintain',body:'Conventional burial avoids a continuous channel, its covers and its drainage points. It still needs correct bedding, utility clearances and repair excavation. Rain and sand symbols do not represent measured conditions.'};
 return s.option==='buried'?{title:'Option One: simpler routine operation',body:'The cut-away exposes sand or fine granular bedding and surround, compacted backfill, pavement sub-base and paving. Material grading and layer thicknesses remain subject to approval. Future repairs require excavation and reinstatement. The 1,000 mm walkway cover and 600 mm trench width are project pricing assumptions.'}:{title:'Option Two: access has conditions',body:'The 600 × 450 mm clear channel provides access when covers are lifted. It also adds covers, frames, supports and drainage to maintain. Working space must be demonstrated with actual fittings and tools.'};
}
