import { SlidersHorizontal, Play, Pause } from 'lucide-react';
import { caption, steps } from './content';
import data from './networkData.json';
import type { CameraAction, ModelSettings, Weather } from './types';
interface Props { settings: ModelSettings; patch: (value:Partial<ModelSettings>)=>void; move: (kind:CameraAction['kind'])=>void; }
export default function ViewDetails({settings,patch,move}:Props){
 const info=caption(settings);
 return <div className="flex flex-col gap-5">
    <div aria-live="polite"><h2 className="text-2xl leading-snug">{info.title}</h2><p className="mt-3">{info.body}</p></div>
    {settings.option==='channel'&&settings.view!=='network'&&<div className="space-y-2"><button className="control w-full selected" onClick={()=>patch({animation:settings.animation==='playing'?'paused':'playing'})}>{settings.animation==='playing'?<Pause size={18}/>:<Play size={18}/>} {settings.animation==='playing'?'Pause animation':settings.animation==='paused'?'Resume animation':'Play cover animation'}</button><p>Animated lift and return. Presentation timing only; no operating time is predicted.</p></div>}
    <div className="space-y-2 border-t border-line pt-4"><button className={`control w-full ${settings.flow?'selected':''}`} aria-pressed={settings.flow} onClick={()=>patch({flow:!settings.flow})}>{settings.flow?'Close water cutaway':'Show water flow'}</button>{(settings.flow||settings.view==='weather'&&settings.weather==='rain')&&<button className="control w-full" onClick={()=>patch({flowPaused:!settings.flowPaused})}>{settings.flowPaused?'Resume water motion':'Pause water motion'}</button>}<p>Illustrative flow direction and timing. Tracers show movement within a full pipe; no velocity, pressure or capacity is calculated.</p></div>
    <div className="border-t border-line pt-4"><h3 className="flex items-center gap-2 font-sans font-semibold"><SlidersHorizontal size={18}/>Explore this view</h3>
     {settings.view==='network'?<div className="mt-3 space-y-3"><label className="block" htmlFor="route">Select a route</label><select id="route" value={settings.selectedPath} onChange={e=>patch({selectedPath:e.target.value})} className="w-full rounded-[5px] border border-line bg-white p-2"><option value="all">All mains and connections</option>{data.paths.map(p=><option key={p.name} value={p.name}>{p.name} · {p.length.toFixed(2)} m</option>)}</select><button className="control w-full" onClick={()=>move('home')}>Focus selected route</button><label className="flex items-center gap-2"><input type="checkbox" checked={settings.showBase} onChange={e=>patch({showBase:e.target.checked})}/>As-built background</label><label className="flex items-center gap-2"><input type="checkbox" checked={settings.showAssets} onChange={e=>patch({showAssets:e.target.checked})}/>Meter and valve symbols</label><div className="space-y-1 border-t border-line pt-3"><p><span className="mr-2 inline-block h-2 w-5 bg-[#0A0A0A]"/>OD110 mains / branches</p><p><span className="mr-2 inline-block h-2 w-5 bg-[#0A0A0A]"/>OD25 villa services</p><p>Lengths are CAD plan measurements.</p></div></div>:null}
     {settings.view==='section'?<div className="mt-3 space-y-3">{settings.option==='channel'&&<button className="control w-full" onClick={()=>patch({opened:!settings.opened,...settings.opened?{flow:false}:{}})}>{settings.option==='channel'?(settings.opened?'Lower covers':'Lift covers'):(settings.opened?'Show backfill':'Show excavated access')}</button>}<p>{settings.option==='channel'?'Closed cover tops are level with the walkway. The front wall and adjacent paving are cut away when open to expose the pipe.':'One half is cut away: bedding, fine granular surround, compacted backfill, sub-base and paving. Layer thicknesses and grading remain unverified.'}</p></div>:null}
     {settings.view==='tapping'?<div className="mt-3 space-y-2">{settings.option==='channel'&&<p><strong>The S-curve allows movement; it is not a vent.</strong> REQ-002 p. 11 requires flexibility at the wall exit. Shape, bend radius and fit need manufacturer / designer verification.</p>}{steps.map((name,i)=><button key={name} onClick={()=>patch({step:i})} aria-pressed={settings.step===i} className={`control w-full justify-start ${settings.step===i?'selected':''}`}>{i+1}. {name}</button>)}</div>:null}
     {settings.view==='weather'?<div className="mt-3 space-y-3"><div className="flex flex-wrap gap-2">{(['dry','rain','sand'] as Weather[]).map(w=><button key={w} className={`control ${settings.weather===w?'selected':''}`} aria-pressed={settings.weather===w} onClick={()=>patch({weather:w})}>{w==='dry'?'Dry':w==='rain'?'Rainwater':'Dust & sand'}</button>)}</div>{settings.option==='channel'&&<button className="control w-full" onClick={()=>patch({opened:!settings.opened,...settings.opened?{flow:false}:{}})}>{settings.opened?'Lower covers':'Lift covers'}</button>}<p>No pump system is proposed. No site-specific drainage fall or outlet has been assumed.</p></div>:null}
    </div>
    <p className="mt-auto border-t border-line pt-4 font-medium text-purple">Not for construction. No hydraulic or drainage-capacity result is implied.</p>
</div>;
}
