import { SlidersHorizontal, Play, Pause } from 'lucide-react';
import { caption, steps } from './content';
import data from './networkData.json';
import type { CameraAction, ModelSettings, Weather } from './types';
interface Props { settings: ModelSettings; patch: (value:Partial<ModelSettings>)=>void; move: (kind:CameraAction['kind'])=>void; }
export default function ViewDetails({settings,patch,move}:Props){
 const info=caption(settings);
 const coversOpen=settings.opened||settings.flow;
 const toggleCovers=()=>patch({opened:!coversOpen,flow:false});
 return <div className="view-details flex flex-col gap-5">
    <div aria-live="polite"><h2 className="text-2xl leading-snug">{info.title}</h2><p className="mt-3">{info.body}</p></div>
    {settings.view==='tapping'&&<p><strong>Orientation:</strong> the saddle sits 45° from the crown towards the villa. A smooth, factory-formed outlet sweep returns to the unchanged wall seal and meter. Exact fitting dimensions, supports and saddle loads require verification.</p>}
    {settings.view==='section'&&<p><strong>Paving reference:</strong> muted warm-grey units informed by the Zone Five photograph. Rectangular units follow the closer photograph; exact dimensions and laying details remain unverified. Green fibre covers remain separate.</p>}
    {settings.option==='channel'&&settings.view!=='network'&&<div className="space-y-2"><button className="control w-full selected" onClick={()=>patch({animation:settings.animation==='playing'?'paused':'playing'})}>{settings.animation==='playing'?<Pause size={18}/>:<Play size={18}/>} {settings.animation==='playing'?'Pause animation':settings.animation==='paused'?'Resume animation':'Play cover animation'}</button><p>Animated lift and return. Presentation timing only; no operating time is predicted.</p></div>}
    <div className="space-y-2 border-t border-line pt-4"><button className={`control w-full ${settings.flow?'selected':''}`} aria-pressed={settings.flow} onClick={()=>patch({flow:!settings.flow})}>{settings.flow?'Close water cutaway':'Show water flow'}</button>{(settings.flow||settings.view==='weather'&&settings.weather==='rain')&&<button className="control w-full" onClick={()=>patch({flowPaused:!settings.flowPaused})}>{settings.flowPaused?'Resume water motion':'Pause water motion'}</button>}<p>Illustrative flow direction and timing. Tracers show movement within a full pipe; no velocity, pressure or capacity is calculated.</p></div>
    <div className="border-t border-line pt-4"><h3 className="flex items-center gap-2 font-sans font-semibold"><SlidersHorizontal size={18}/>Explore this view</h3>
     {settings.view==='network'?<div className="mt-3 space-y-3"><label className="block" htmlFor="route">Select a route</label><select id="route" value={settings.selectedPath} onChange={e=>patch({selectedPath:e.target.value})} className="w-full rounded-[5px] border border-line bg-white p-2"><option value="all">All mains and connections</option>{data.paths.map(p=><option key={p.name} value={p.name}>{p.name} · {p.length.toFixed(2)} m</option>)}</select><button className="control w-full" onClick={()=>move('home')}>Focus selected route</button><label className="flex items-center gap-2"><input type="checkbox" checked={settings.showBase} onChange={e=>patch({showBase:e.target.checked})}/>As-built background</label><label className="flex items-center gap-2"><input type="checkbox" checked={settings.showAssets} onChange={e=>patch({showAssets:e.target.checked})}/>Meter and valve symbols</label><div className="space-y-1 border-t border-line pt-3"><p><span className="mr-2 inline-block h-2 w-5 bg-[#0A0A0A]"/>OD110 mains / branches</p><p><span className="mr-2 inline-block h-2 w-5 bg-[#0A0A0A]"/>OD25 villa services</p><p>Lengths are CAD plan measurements.</p></div></div>:null}
     {settings.view==='section'?<div className="mt-3 space-y-3">{settings.option==='channel'&&<button className="control w-full" onClick={toggleCovers}>{settings.option==='channel'?(coversOpen?'Lower covers':'Lift covers'):(settings.opened?'Show backfill':'Show excavated access')}</button>}<p>{settings.option==='channel'?'Closed cover tops are level with the walkway. Interlock connects the channel to the villa frontage. The asphalt road is on the opposite side. Narrow inspection slots expose the service connections.':'One half is cut away: bedding, fine granular surround, compacted backfill, sub-base and paving. Layer thicknesses and grading remain unverified.'}</p></div>:null}
     {settings.view==='run'?<div className="mt-3 space-y-3">{settings.option==='channel'&&<button className="control w-full" onClick={toggleCovers}>{coversOpen?'Lower covers':'Lift covers'}</button>}<p>Flow starts automatically. Follow the blue water from Main C through separate Tee A and Tee B connections into the two villa-side pipelines. Main B has a buried sleeved connecting stub. Each villa service stays on its own side of the asphalt road. Covers are omitted while flow is shown. Chamber size, valve type, road width and row offset remain illustrative.</p><p>Choose <strong>Fly to a component</strong> above the model to inspect either side’s pipeline, chamber or villa connection.</p></div>:null}
     {settings.view==='tapping'?<div className="mt-3 space-y-2">{settings.option==='channel'&&<p><strong>Formed sweep, not a tight cold bend.</strong> The existing wall seal and meter positions are retained. The manufacturer must confirm the fitting, sweep and support arrangement; the model does not establish a stress-free installation.</p>}{steps.map((name,i)=><button key={name} onClick={()=>patch({step:i,flow:i>=3,flowPaused:false,animation:'off'})} aria-pressed={settings.step===i} className={`control w-full justify-start ${settings.step===i?'selected':''}`}>{i+1}. {name}</button>)}</div>:null}
     {settings.view==='weather'?<div className="mt-3 space-y-3"><div className="flex flex-wrap gap-2">{(['dry','rain','sand'] as Weather[]).map(w=><button key={w} className={`control ${settings.weather===w?'selected':''}`} aria-pressed={settings.weather===w} onClick={()=>patch({weather:w})}>{w==='dry'?'Dry':w==='rain'?'Rainwater':'Dust & sand'}</button>)}</div>{settings.option==='channel'&&<button className="control w-full" onClick={toggleCovers}>{coversOpen?'Lower covers':'Lift covers'}</button>}<p>No pump system is proposed. No site-specific drainage fall or outlet has been assumed.</p></div>:null}
    </div>
    <p className="mt-auto border-t border-line pt-4 font-medium text-purple">Not for construction. No hydraulic or drainage-capacity result is implied.</p>
</div>;
}
